@startuml task_manager
title Task Manager
skin rose


participant Task_Manager as Task
participant Subtask

activate Redis

activate Task
Task -> Redis: query_module()
return module_list{\n"module_name",\n"version"\n}

Task -> Redis: query_task()
return task_list{\n"task_name",\n"type"(trigger or interval),\n"interval"(interval time in seconds, 0 trigger, !0 interval)\n}

loop !SHUTDOWN_FLAG
    note over Task: 除非接收到结束标志，否则将一直执行任务循环
    opt LIB_UPDATE_FLAG
        note over Task: 用于查询库更新并更新库
        Task -> Redis: query_for_update_lib()
        return Library_name
        Task -> Task: Reload(Library_name)
    end
    alt count % 10 == 0
        Task -> Task: Checking task.
        opt Time_trigger
            Task -> Subtask: start task.
            activate Subtask
            ...After task period...
            return task finished & task_period in seconds
            deactivate Subtask
        end
    else count % 1800 == 0
        Task -> Redis: Checking task schedule table for update.
    Task -> Task: sleep(1s) count += 1
end
Task -> Task: Task pipline shutdown. No action. TBD
deactivate Task

deactivate Redis

@enduml